print("Bom dia")
print("turma")
print("Python é bem legal! Mas não o 'legal' como dizem para outras coisas")
print("" "<- está vazio")
print("O mais 'legal' é aprender uma linguagem poderosa e do futuro")